config/routes.rb
Rails.application.routes.draw do

  root to: 'messages#index'
  resources :messages, only: [:index, :create] 
  get '/messages/new_messages', to: 'messages#new_messages'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
	validates :user_id, presence: true
	validates :text, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	before_create :create_remember_token
	has_many :messages
	validates :name, presence: true, uniqueness: true
	has_secure_password
	validates :password, length: { minimum: 6 }
  validates :password_confirmation, confirmation: true
	
	def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsAction
  helper_method :current_user, :signed_in?

  def signed_in?
    !current_user.nil?
  end
  def current_user
  	remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
end

app/controllers/concerns/sessions_action.rb
module SessionsAction
extend ActiveSupport::Concern

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end
  def current_user=(user)
    @current_user = user
  end
  def sign_out
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  def signed_in_user
      redirect_to signin_path, notice: "If you want to use the chat, please sign in." unless signed_in?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :signed_in_user

  def index
    @messages = Message.last(5)
  end

  def new_messages
    if params[:id].to_i != 0
      @new_messages = Message.where("id > ?", params[:id].to_i)
    else
      redirect_to messages_path
    end
  end

  def create
    @message = Message.new(message_params)
    @message.user = current_user
    @message.save
  end

  private
    def message_params
    	params.require(:message).permit(:text)
    end
 
end
 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to messages_path
    else
      flash.now[:error] = 'Invalid name|password combination'
      render 'new'
    end
  end

  def destroy
  	sign_out
    redirect_to signin_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: :index
 
  def index
    @users = User.all
  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
    	redirect_to messages_path
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :password,:password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <ul class="nav navbar-nav">
      <% if signed_in? %>
        <li><%= link_to "Users", users_path unless params.has_value?("users")%></li>
        <li><%= link_to "Chat", messages_path unless params.has_value?("messages")%></li>
        <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
      <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chatroom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_message.html.erb
<div class="message" data-id="<%= message.id %>">
  <span class="time"><%= message.created_at.strftime("[%H:%M:%S]") %></span>
  <span class="user"><%= message.user.name%></span>
  <%= message.text%> 
</div>

app/views/messages/create.js.erb
$("#message_text").val(''); 
getNewMessage();

app/views/messages/index.html.erb
  <h1>Chat</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="chatmessages" id="messages">
        <%= render @messages %>
      </div>
      <%= form_for :message, url: messages_path, :remote => true do |f| %>
        <%= f.text_area :text, :cols => "60", :rows => "4", :placeholder=>"New message", class: "form-control" %>
        <%= f.submit "Send", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

app/views/messages/index.js.erb
$('#messages').html("<%= j render(@messages) %>");

app/views/messages/new_messages.js.erb
$('#messages').append("<%= j render(@new_messages) %>");

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
    The form contains <%= pluralize(@user.errors.count, "error") %>.
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.name %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary"%>
    <% end %>
  </div>
</div>